socket:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simplefarm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: org.milkteaboy.simplefarm.entity
  configuration:
    map-underscore-to-camel-case: true